pip install gdown
pip install pandas
pip install scikit-learn
pip install scipy 
pip install opencv-python
pip install seaborn
pip install imgaug
pip install SimpleITK
pip install dask
pip install diagnostics